INCLUDES = \
	-I$(top_builddir)/glib	-I$(top_srcdir)/glib	\
	-I$(top_builddir)/pango	-I$(top_srcdir)/pango	\
	-I$(top_builddir)/atk	-I$(top_srcdir)/atk	\
	-I$(top_builddir)/gdk	-I$(top_srcdir)/gdk	\
	-I$(top_builddir)/gtk	-I$(top_srcdir)/gtk	\
	$(GTKMM_CFLAGS) $(GTHREAD_CFLAGS)

LIBS =	$(top_builddir)/glib/glibmm/libglibmm-2.0.la	\
	$(top_builddir)/pango/pangomm/libpangomm-1.0.la	\
	$(top_builddir)/atk/atkmm/libatkmm-1.0.la	\
	$(top_builddir)/gdk/gdkmm/libgdkmm-2.0.la	\
	$(top_builddir)/gtk/gtkmm/libgtkmm-2.0.la	\
	$(GTKMM_LIBS)

