INCLUDES = \
	-I$(top_builddir)/pango	-I$(top_srcdir)/pango	\
	-I$(top_builddir)/gdk	-I$(top_srcdir)/gdk	\
	-I$(top_builddir)/gtk	-I$(top_srcdir)/gtk	\
	$(GTKMM_CFLAGS) $(GTHREAD_CFLAGS)

LIBS = \
	$(top_builddir)/pango/pangomm/libpangomm-1.4.la	\
	$(top_builddir)/gdk/gdkmm/libgdkmm-2.4.la	\
	$(top_builddir)/gtk/gtkmm/libgtkmm-2.4.la	\
	$(GTKMM_LIBS)

