#! /bin/sh

# This installs MSVC-built libraries of a module such as libsigc++, glibmm or
# gtkmm into the MSVC subdirectory

module=$1
toolset=$2

# Assume all the other libraries are at same point as gtkmm:
basepath=../..

# TODO: Automatically find latest version of package: First try SVN checkout, then look for latest installed tarball version.
case $module in
    libsigc++)
	# Path to extracted tarball or SVN checkout
	sourcepath="${basepath}/libsigc++-2.2.4.2"
	# Basename of DLL
	basename='sigc'
	# Version tag of DLL name
	vername='2_0'
	# Abiname of package
	abiname='sigc++-2.0'
	# Subdirectory in MSVC_Net2005
	subdir='.'
	;;
    glibmm)
	sourcepath="${basepath}/glibmm-2.22.1"
	basename='glibmm'
	vername='2_4'
	abiname='glibmm-2.4'
	subdir='glibmm'
	;;
    giomm)
	sourcepath="${basepath}/glibmm-2.22.1"
	basename='giomm'
	vername='2_4'
	abiname='giomm-2.4'
	subdir='giomm'
	;;
    cairomm)
	sourcepath="${basepath}/cairomm"
	basename='cairomm'
	vername='1_0'
	abiname='cairomm-1.0'
	subdir='cairomm'
	;;
    pangomm)
	sourcepath="${basepath}/pangomm-2.26.0"
	basename='pangomm'
	vername='1_4'
	abiname='pangomm-1.4'
	subdir='pangomm'
	;;
    atkmm)
	sourcepath="${basepath}/gtkmm-2.18.2"
	basename='atkmm'
	vername='1_6'
	abiname='atkmm-1.6'
	subdir='atkmm'
	;;
    gdkmm)
	sourcepath="${basepath}/gtkmm-2.18.2"
	basename='gdkmm'
	vername='2_4'
	abiname='gdkmm-2.4'
	subdir='gdkmm'
	;;
    gtkmm)
	sourcepath="${basepath}/gtkmm-2.18.2"
	basename='gtkmm'
	vername='2_4'
	abiname='gtkmm-2.4'
	subdir='gtkmm'
	;;
    libglademm)
	sourcepath="${basepath}/libglademm-2.6.7"
	basename='glademm'
	vername='2_4'
	abiname='glademm-2.4'
	subdir='libglademm'
	;;
    libxml++)
	sourcepath="${basepath}/libxml++-2.26.1"
	basename='xml++'
	vername='2_6'
	abiname='libxml++-2.6'
	subdir='libxml++'
	;;
    *)
	echo "Module $module not known"
	exit 1
	;;
esac

case $toolset in
    vc80)
	vcdir='MSVC_Net2005'
	;;
    vc90)
	vcdir='MSVC_Net2008'
	;;
    *)
	echo "Toolset $toolset not known"
	exit 1
	;;
esac

#echo "Source Path: $sourcepath"
#echo "Basename: $basename"
#echo "Abiname: $abiname"
#echo "Subdir: $subdir"

targetpath=MSVC

mkdir -p "${targetpath}" || exit 1
cp "$sourcepath/$vcdir/$subdir/Release/${basename}-${toolset}-${vername}.dll" "$targetpath" || exit 1
cp "$sourcepath/$vcdir/$subdir/Debug/${basename}-${toolset}-d-${vername}.dll" "$targetpath" || exit 1
cp "$sourcepath/$vcdir/$subdir/Debug/${basename}-${toolset}-d-${vername}.pdb" "$targetpath" || exit 1

mkdir -p "${targetpath}/lib" || exit 1
cp "$sourcepath/$vcdir/$subdir/Release/${basename}-${toolset}-${vername}.lib" "$targetpath" || exit 1
cp "$sourcepath/$vcdir/$subdir/Debug/${basename}-${toolset}-d-${vername}.lib" "$targetpath" || exit 1

# Configfile is used from mingw, thus commented out:
#configfile=$sourcepath/MSVC_Net2005/$subdir/*config.h
#if test -f configfile; then
#	mkdir -p $targetpath/lib/${abiname}/include/ || exit 1
#	cp $configfile $targetpath/lib/${abiname}/include/ || exit 1
#fi
